### ISSUE TITLE
能获取到和下载但是不能显示到muzei的bug

### ISSUE THREAD

**Issue by Aragamiz** [moonheart/PixivForMuzeiPlus#1]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String a.a.a.a.a.a.a.b()' on a null object reference
	at moe.democyann.pixivformuzeiplus.PixivSource$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:818)

在pixiv文件夹的图片大约到达360+的时候，就不会显示在muzei之中，只会不停的下载。
此时muzei和插件卡死，并抛出上面的异常

**Comment by moonheart** [comment]
我的目前有7k+图片仍然能够正常使用，你那是不是有什么限制了后台？

**Comment by Aragamiz** [comment]
没有这样的。。。内存管理的都避开了muzei和插件。。
偶尔见到error1034

**Comment by moonheart** [comment]
可以把logcat消息发上来看看吗，我需要定位问题

**Comment by Aragamiz** [comment]
没找到如何重现bug。。。重现了再发把。。QAQ
