### ISSUE TITLE
推荐模式存在问题

### ISSUE THREAD

**Issue by Think0508** [moonheart/PixivForMuzeiPlus#3]
您好，我使用时发现收藏夹和猜你喜欢的推荐模式均无法正常使用，依然会在top50乱跳。流程是:安装这个版本-输入账号密码-选择猜你喜欢，muzei中切图。一开始会在top50中跳几张，然后正常切了几张图，之后就总是显示retry(retry后依然不行)。接着切图，就无限在top50里跳转了。收藏夹同理。不知我需要提供哪些信息能够帮得上忙？
机型:红米n4x 骁龙625 Android7.0 空间足够 翻墙和不翻(改hosts)均尝试 hosts能够直连手机和网页版pixiv成功 其他同类插件可以正常切图

**Comment by Think0508** [comment]
不好意思打扰了，刚刚来回切换了几次网络状态后发现又可以正常使用了……很诡异。估计是retry时候切换翻墙导致的。

**Comment by moonheart** [comment]
网络请求失败（网络本身问题/图片不存在/请求403）等，都会导致fallback到Top模式，这个时候可以切换一下网络环境，然后再点击下一张（可能要多点几次，间隔5s已上）
